### GET Orders
GET http://localhost:3000/orders

### GET Order Detail
GET http://localhost:3000/orders/1

### GET Cartons
GET http://localhost:3000/cartons

### Assign Carton
POST http://localhost:3000/orders/carton
Content-Type: application/json

{
  "order_id": 1,
  "carton_id": "L",
  "created_by": "agus.stiyo@anteraja.id"
}