@local = http://localhost:3000
@prod = https://mock-api-anteraja.vercel.app

@host = {{prod}}

### GET Orders
GET {{host}}/orders

### GET Order Detail
GET {{host}}/orders/1

### GET Cartons
GET {{host}}/cartons

### Assign Carton
POST {{host}}/orders/carton
Content-Type: application/json

{
  "order_id": 1,
  "carton_id": "L",
  "created_by": "agus.stiyo@xyz.id"
}